"use client";
import { useActionState, useState } from "react";
import { Check, Copy, Plus, X } from "lucide-react";
import { createProject } from "@/app/(dashboard)/projects/actions";
import { Button } from "@/components/ui/button";

export function CreateProject() {
  const [open, setOpen] = useState(false); const [state, action, pending] = useActionState(createProject, {}); const [copied, setCopied] = useState<string>();
  const copy = async (value: string, field: string) => { await navigator.clipboard.writeText(value); setCopied(field); setTimeout(() => setCopied(undefined), 1500); };
  return <><Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" />New project</Button>{open ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" onMouseDown={(e) => e.target === e.currentTarget && setOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="project-dialog-title" className="w-full max-w-lg rounded-lg border bg-[var(--surface)] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 id="project-dialog-title" className="text-lg font-semibold">Create project</h2><p className="text-sm text-[var(--muted)]">Connect an application to Pulse.</p></div><button onClick={() => setOpen(false)} aria-label="Close"><X className="h-5 w-5" /></button></div>
    {state.apiKey ? <div className="mt-6 space-y-5"><p className="text-sm text-[var(--accent-strong)]">Project created. Store this key now; Pulse will not show it again.</p><SecretRow label="Project ID" value={state.projectId!} onCopy={() => copy(state.projectId!, "id")} copied={copied === "id"} /><SecretRow label="Ingestion API key" value={state.apiKey} onCopy={() => copy(state.apiKey!, "key")} copied={copied === "key"} /><pre className="overflow-x-auto rounded-md bg-[var(--background)] p-4 text-xs"><code>{`curl -X POST $PULSE_URL/api/events \\\n  -H "Authorization: Bearer $PULSE_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{"method":"GET","path":"/health","statusCode":200,"responseTime":42}'`}</code></pre><Button className="w-full" onClick={() => location.reload()}>Done</Button></div> : <form action={action} className="mt-6 space-y-4"><Field name="name" label="Project name" placeholder="Payments API" /><Field name="url" label="Project URL" type="url" placeholder="https://api.example.com" /><label className="block text-sm font-medium">Environment<select name="environment" className="mt-1.5 h-10 w-full rounded-md border bg-[var(--background)] px-3"><option value="production">Production</option><option value="staging">Staging</option><option value="development">Development</option></select></label>{state.error ? <p role="alert" className="text-sm text-[var(--danger)]">{state.error}</p> : null}<Button disabled={pending} className="w-full">{pending ? "Creating..." : "Create project"}</Button></form>}
  </div></div> : null}</>;
}
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="block text-sm font-medium">{label}<input required {...props} className="mt-1.5 h-10 w-full rounded-md border bg-[var(--background)] px-3" /></label>; }
function SecretRow({ label, value, onCopy, copied }: { label: string; value: string; onCopy: () => void; copied: boolean }) { return <div><span className="text-xs text-[var(--muted)]">{label}</span><div className="mt-1 flex items-center gap-2 rounded-md border bg-[var(--background)] p-2"><code className="min-w-0 flex-1 truncate text-xs">{value}</code><button onClick={onCopy} aria-label={`Copy ${label}`} className="p-1">{copied ? <Check className="h-4 w-4 text-[var(--accent)]" /> : <Copy className="h-4 w-4" />}</button></div></div>; }
